function ModPar = calFWTtank (wavetype, calcType)

% This list below is prepared for simulation of hydrodynamic response of a
% floating spar (representing Hywind floating wind turbine -FWT) in a wave
% tank environment 

% 06/04/2021 @ Franklin Court, Cambridge  [J Yang] 
% 09/04/2021 @ Franklin Court, Cambridge  [J Yang] --> updated for the wave
% tank testing environment 

ModPar = struct ( ...
         'Struct_type',  1 ,                ...   % choose struture type FWT == 1
          'isModelTest', 1,                 ...   % choose model testing for wave tank model
     ... ---------------------------------------------------------------
     ... % options to control    
     ... --------------------------------------------------------------- 
         'wavetype'   ,  wavetype ,                ...   % choose wave type, regular == 1, random == 2
         'calcType' ,    calcType ,                ...   % choose freuqency == 1 or time == 2
     ... % calculation parameters
         'om_range'  ,  (0.1:0.05:2)*2*pi,      ...   % choose frequency range (this only controls harmonic wave)
         'tmax'      ,   1/0.1*5,        ...     
         'dtScale'    ,  20,                ...   % scale time step, bigger --> finer 
     ... % parameters of random sea states 
         ... % combination of Hs = 1.5 and Tz = 7.5 have high occurance according to scatter diagram for North Atlantic (DNVGL-C205)
         'wavecode' ,    1 ,                 ...  % choose Jonswap wave (at the moment only this representative sea state)
        'jonswapHs'   , 1.5 ,                ...  % wave height
        'jonswapTz'   , 7.5,                  ...  % zero up-crossing period Tz, and peak wave period Tp = 1.2859*Tz (for the Jonswap parameter used )    
     ... ---------------------------------------------------------------
     ... % to test the code, the following parameters should be left as it is 
     ... ---------------------------------------------------------------    
     ... % options 
         'bendingCalc', 'IR' ,...   
         'bodyflex' ,    0 , ...
         'aw'      ,    1 , ...
         'Nfft'    ,   2^11, ...
         'Nwin'     ,  2^5,  ...
         'Ndof'     ,   2,   ...
         'Nvb'     ,	2,   ...
         'wLim'     ,   5,   ...
         'g'        ,  9.81, ...
         'typeIntTLP', 'decay with plateau',...
     ... % Morison parameters
        'Ca'         ,  1, ...
        'Cd'         ,  1, ...
     ... % material parameters
        'rho'        ,  1.18e3 , ...
        'rho_f'      ,  1.025e3, ...
        'rho_oil'    ,  0,  ...
        'E'          ,  3e9 ,   ...
     ... % platform related 
        'T0'         ,  0,  ...
        'T_TLP'      ,  6:1:18,      ...
        'H_TLP'      ,  zeros(size([6:1:18])),     ...
        'gamma_TLP' ,  zeros(size([6:1:18])),      ...
     ... % geometries of structure
         'Nsec'     ,   2,      ...
         'rhoC'     ,   [1 0],       ...
        'Din'        ,  [0.09-3.5e-3*2 0] ,   ...
        'Dout'       ,  [0.09 0],   ...
        'De'         ,  [0.09 0],    ...
         'L'       ,   [1 0.2],       ...
         'Li'       ,   [0.01 0.01],       ...
         'L1'       ,   0.2,      ...
         'L2'       ,   1,     ...
     ... % model testing related 
         'L_b'     ,   0.15,      ...
         'mb'     ,   3,          ...
          'd'     ,   1,          ...
     ... % 
         's_alpha' ,    0 ); 
     
        
        