% This list below is prepared for simulation of hydrodynamic response of a
% floating spar (representing Hywind floating wind turbine -FWT)

% 06/04/2020 @ Franklin Court, Cambridge  [J Yang] 

ModPar = struct ( ...
         'Struct_type',  1 ,                ...   % choose struture type FWT == 1
     ... ---------------------------------------------------------------
     ... % options to control    
     ... --------------------------------------------------------------- 
         'wavetype'   ,  2 ,                ...   % choose wave type, regular == 1, random == 2
         'calcType' ,    2 ,                ...   % choose freuqency == 1 or time == 2
     ... % calculation parameters
         'om_range'  ,  (0.02:0.02:1),      ...   % choose frequency range 
         'tmax'      ,  2*pi/0.02*5,        ...     
         'dtScale'    ,  20,                ...   % scale time step, bigger --> finer 
     ... % parameters of random sea states 
         ... % combination of Hs = 1.5 and Tz = 7.5 have high occurance according to scatter diagram for North Atlantic (DNVGL-C205)
        'wavecode' ,    1 ,                 ...  % choose Jonswap wave (at the moment only this representative sea state)
        'jonswapHs'   , 1.5 ,                ...  % wave height
        'jonswapTz'   , 7.5,                  ...  % zero up-crossing period Tz, and peak wave period Tp = 1.2859*Tz (for the Jonswap parameter used )    
     ... ---------------------------------------------------------------
     ... % to test the code, the following parameters should be left as it is 
     ... ---------------------------------------------------------------    
     ... % options 
         'bendingCalc', 'IR' ,...   
         'bodyflex' ,    0 , ...
         'aw'      ,    1 , ...
         'Nfft'    ,   2^11, ...
         'Nwin'     ,  2^5,  ...
         'Ndof'     ,   2,   ...
         'Nvb'     ,	2,   ...
         'wLim'     ,   5,   ...
         'g'        ,  9.81, ...
         'typeIntTLP', 'decay with plateau',...
         'isModelTest', 0, ...
     ... % Morison parameters
        'Ca'         ,  1, ...
        'Cd'         ,  1, ...
     ... % material parameters
        'rho'        ,  2.7e3 , ...
        'rho_f'      ,  1.025e3, ...
        'rho_oil'    ,  0,  ...
        'E'          ,  2e10 ,   ...
     ... % platform related 
        'T0'         ,  0,  ...
        'T_TLP'      ,  6:1:18,      ...
        'H_TLP'      ,  zeros(size([6:1:18])),     ...
        'gamma_TLP' ,  zeros(size([6:1:18])),      ...
     ... % geometries of structure
         'Nsec'     ,   3,      ...
         'rhoC'     ,   [1 1 125],       ...
        'Din'        ,  [6 8.3 8.3]-0.2,   ...
        'Dout'       ,  [6 8.3 8.3],   ...
        'De'         ,  [6 8.3 8.3],    ...
         'L'       ,   [70 90 5],       ...
         'Li'       ,   [1 1 1],       ...
         'L1'       ,   63,      ...
         'L2'       ,   7+90+5,     ...
     ... % model testing related 
         'L_b'     ,  [],      ...
         'mb'     ,   [],          ...
          'd'     ,   [],          ...         
     ... % 
         's_alpha' ,    3e4); 
 

        
        