
ModPar = struct ( ...
          ... % options 
         'bendingCalc', 'IR' ,...
         'wavetype'   ,  1 , ...
         'Struct_type',  1 , ...
         'calcType' ,    1 , ...
         'wavecode' ,    1 , ...
         'bodyflex' ,    0 , ...
         'aw'      ,    1 , ...
         'Nfft'    ,   2^6, ...
         'Nwin'     ,	[],  ...
         'Ndof'     ,   2,   ...
         'Nvb'     ,	2,   ...
         'wLim'     ,   5,   ...
         'g'        ,  9.81, ...
         'typeIntTLP', 'decay with plateau',...
         'isModelTest', 0, ...
         ... % List of sea states 
        'jonswapHs'   , 2.5000  , ...
        'jonswapTz'   , 7.6352  , ...
        'jonswapPSS'  , 0.3613  , ...
        'jonswapNSS'  , 1, ...
         ... % Morison parameters
        'Ca'         ,  1, ...
        'Cd'         ,  1, ...
         ... % material parameters
        'rho'        ,  7.84e3 , ...
        'rho_f'      ,  1.025e3, ...
        'rho_oil'    ,  0.92e3,  ...
        'E'          ,  2e11 ,   ...
         ... % calculation parameters
         'om_range'  ,  1,      ...
         'tmax'      ,  [],      ...
         'dtspan'    ,  [],      ...
         ... % platform related 
        'T0'         ,  4905e3,  ...
        'T_TLP'      ,  [],      ...
        'H_TLP'      ,  [],      ...
        'gamma_TLP' ,  [],      ...
         ... % geometries of structure
        'Din'        ,  0.374,   ...
        'Dout'       ,  0.406,   ...
        'De'         ,  0.66,    ...
         'Li'       ,   1,       ...
         'L1'       ,   20,      ...
         'L2'       ,   100,     ...
         'Nsec'     ,   1,       ...
         'rhoC'     ,   1,       ...
         ... % 
         's_alpha' ,    1,       ...
         'd'        ,   []       ); 
     
 Out = maincode (ModPar);    
        
        